/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package base;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        GameOfLifeMain classUnderTest = new GameOfLifeMain();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
