/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package base;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class GameOfLifeMain {
    private static Logger LOGGER = LoggerFactory.getLogger(GameOfLifeMain.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        LOGGER.debug(new GameOfLifeMain().getGreeting());
    }
}
