/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package base;

public class GameOfLifeMain {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new GameOfLifeMain().getGreeting());
    }
}
